#!/usr/bin/env bash
# Accepts arguments. Audit the domain of all subdomains

audit_domain () {
	if [ "$1" ]
	then
		if [ "$2" ]
		then
			subdomains=("$2")
		else
			subdomains=("www" "lb-01" "web-01" "web-02")
		fi


		for sub in "${subdomains[@]}"
		do
			typ=$(dig "$sub.$1" | grep -A1 'ANSWER SECTION' | awk '{print $4}' | tail -1)
			addr=$(dig "$sub.$1" | grep -A1 'ANSWER SECTION' | awk '{print $5}' | tail -1)

			echo "The subdomain $sub is a $typ record and points to $addr"
		done
	fi

}

audit_domain "$1" "$2"
