#!/usr/bin/env bash
# Install nginx listening on port 80 on a server web-01
# curl request shoul return a page with string "Hello World"

sudo apt update
sudo apt -y install nginx

echo "Hello World!" > index.html
sudo cp index.html /var/www/html/

echo "server {
	listen     80 default_server;
	listen     [::]:80 default_server;
	root       /var/www;
	index.html index.htm;
} > /etc/nginx/sites-available/default"
services nginx restart
