#!/usr/bin/env bash
# Redirects yo another page

sudo apt-get update
sudo apt-get install -y nginx

mkdir -p /var/www/root
echo "Hello World!" > /var/www/root/index.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/root;
	index index.html index.htm;

	location /redirect_me {
		return 301 https://www.example.com;
	}
}" > /etc/nginx/sites-available/default
service nginx restart
