#!/usr/bin/env bash
# to have a 404 pagewith twxt

sudo apt-get update
sudo apt-get install -y nginx

mkdir -p /var/www/root
echo "Hello World!" > /var/www/root/index.html
echo "Ceci n'est pas une page" > /var/www/root/404.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/root;
	index index.html index.htm;
	
	location /redirect_me {
		return 301 https://www.example.com;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/root;
		internal;
	}
}" > /etc/nginx/sites-available/default
service nginx restart
