#!/bin/usr/env bash
# configure Nginx with a custom header: X-Served_by = server's hostname

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello world!" > index.html
sudo cp index.html /var/www/html/
echo "Ceci n'est pas une page" > 404.html
sudo cp 404.html /var/www/html/
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	add_header X-Served-By $HOSTNAME;

	root /var/www/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 https://www.google.com;
	}

	error_page 404 /404.html
	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default
sudo service nginx restart
