#!/usr/bin/env bash
# install and configure HAproxy load balancer on a server lb-01
# Using roundrobin balancing algorithm
# HAproxy can bemanaged via an init script

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get update
sudo apt-get -y install haproxy=2.6.\*

echo "ENABLED=1" >> /etc/default/haproxy
cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log	local0
    log /dev/log	local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon


defaults
    log	    global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    mode http
    bind :80
    default_backend servers

backend servers
    balance roundrobin
    server 148553-web-01 34.224.94.161 check
    server 148553-web-02 35.153.232.246 check
EOF
sudo service haproxy start
