#!/usr/bin/env bash
# install and configure HAproxy load balancer on a server lb-01
# Using roundrobin balancing algorithm
# HAproxy can bemanaged via an init script

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt update
sudo apt -y install haproxy=2.6.\*

sudo cp -a /etc/haproxy/haproxy.cfg{,.old_cpy}
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo "frontend server_front
    mode http
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 34.224.94.161 check
    server web-02 35.153.232.246 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
