#!/usr/bin/env bash
# Pings (using ICMP) an IP address passed as arg
# displays "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}" when arg is null
if [ $# -eq 0 ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
        ping -c 5 "$1"
fi
