#!/usr/bin/env bash
# Nginx running and listening on port *0 of all servers active IPv4sudo
sudo sed -i "s+include /etc/nginx/sites-enabled/*;+include /etc/nginx/sites-available/*;\n\tinclude /etc/nginx/sites-enabled/*;+" /etc/nginx/nginx.conf
sudo service restart
