#!/usr/bin/env bash
# Print "Best School" 10 times using while cond statement
# print other test in line 4 and 8
i=0
while ((i<10))
do
    if ((i == 3))
    then
        echo "bad luck"
    elif ((i == 7))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
