#!/usr/bin/env bash
# configure an ubuntu server by resolving IP address of urls
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" >> ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
