#!/usr/bin/env bash
#confihure nginx to run as the user

pkill apache2
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
systemctl restart ngin
