#!/usr/bin/env bash
#confihure nginx to run as the user
pkill apache2
sudo sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default
sudo chmod 700 /etc/nginx/nginx.conf
service nginx reload
service nginx restart
