#!/usr/bin/env bash
#confihure nginx to run as the user
pkill apache2
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/defaulti
chown nginx:nginx /etc/nginx/nginx.conf
chmod 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
